config/routes.rb
Rails.application.routes.draw do
  resources :empleados
  resources :sucursals
  devise_for :personas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sucursals#index'
  post '/verificarEmpresa', to: 'admin#verificarEmpresa', as: 'verificar_empresa'
  post '/verificarSucursal', to: 'admin#verificarSucursal', as: 'verificar_sucursal'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empleado.rb
class Empleado < ApplicationRecord
  belongs_to :sucursal
  validates :nombre, presence: true
  validates :rfc, presence: true
end

app/models/persona.rb
class Persona < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :sucursals
  validates :nombre, presence: true
  validates :apellido_paterno, presence: true
  validates :apellido_materno, presence: true
  validates :rfc, presence: true
  validates :nombre_empresa, presence: true, uniqueness: {scope: :rfc}

  def to_text
    return self.nombre + ' ' + self.apellido_paterno + ' ' + self.apellido_materno
  end

end

app/models/sucursal.rb
class Sucursal < ApplicationRecord
  belongs_to :persona
  has_many :empleados
  validates :nombre, presence: true
  validates :calle, presence: true
  validates :colonia, presence: true
  validates :num_exterior, presence: true, numericality: { only_integer: true }
  validates :num_interior, numericality: { only_integer: true }, allow_blank: true
  validates :codigo_postal, presence: true, numericality: { only_integer: true }
  validates :ciudad, presence: true
  validates :pais, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    skip_before_action :authenticate_persona!, only: [:verificarEmpresa, :index]
    
    def index
        if !persona_signed_in?
            redirect_to new_persona_session_path
        end
    end

    #Regresa true si es posible crear usuario con nombre de empresa única
    def verificarEmpresa
        nombreEmpresa = params[:nombre_empresa]
        email = params[:email]
        rfc = params[:rfc]
        respond_to do |format|
            if nombreEmpresa.present? && rfc.present?
                validateEmpresa = !Persona.find_by(nombre_empresa: nombreEmpresa, rfc: rfc).present?
            else
                validateEmpresa = nil
            end
            format.json { render json: validateEmpresa, status: :ok, location: verificar_empresa_path }
        end
    end

    #Regresa true si es posible crear sucursal con nombre único
    def verificarSucursal
        nombreSucursal = params[:nombre_sucursal]
        respond_to do |format|
            if nombreSucursal.present?
                validateSucursal = !Sucursal.find_by(nombre: nombreSucursal).present?
            else
                validateSucursal = nil
            end
            format.json { render json: validateSucursal, status: :ok, location: verificar_sucursal_path }
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_persona!
    before_action :configure_permitted_parameters, if: :devise_controller?

    def index
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nombre, :apellido_materno, 
        :apellido_paterno, :rfc, :nombre_empresa])
    end
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: %i[ show edit update destroy ]

  # GET /empleados or /empleados.json
  def index
    @empleados = Empleado.all
  end

  # GET /empleados/1 or /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
  end

  # POST /empleados or /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)

    respond_to do |format|
      if @empleado.save
        format.html { redirect_to @empleado, notice: "Empleado creado exitosamente" }
        format.json { render :show, status: :created, location: @empleado }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empleados/1 or /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to root_path, notice: "Empleado actualizado exitosamente" }
        format.json { render :show, status: :ok, location: @empleado }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1 or /empleados/1.json
  def destroy
    @empleado.destroy
    respond_to do |format|
      format.html { redirect_to empleados_url, notice: "Empleado eliminado exitosamente" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def empleado_params
      params.require(:empleado).permit(:nombre, :rfc, :nombre_puesto, :sucursal_id)
    end
end

app/controllers/sucursals_controller.rb
class SucursalsController < ApplicationController
  skip_before_action :authenticate_persona!, only: [:index]
  before_action :set_sucursal, only: %i[ show edit update destroy ]

  # GET /sucursals or /sucursals.json
  def index
    if !persona_signed_in?
      redirect_to new_persona_session_path
    end
    @sucursals = Sucursal.all
  end

  # GET /sucursals/1 or /sucursals/1.json
  def show
  end

  # GET /sucursals/new
  def new
    @sucursal = Sucursal.new
    @persona_id = current_persona.id
  end

  # GET /sucursals/1/edit
  def edit
    @persona_id = @sucursal.persona_id
  end

  # POST /sucursals or /sucursals.json
  def create
    @sucursal = Sucursal.new(sucursal_params)

    respond_to do |format|
      if @sucursal.save
        format.html { redirect_to @sucursal, notice: "Sucursal creada exitosamente" }
        format.json { render :show, status: :created, location: @sucursal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sucursal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sucursals/1 or /sucursals/1.json
  def update
    respond_to do |format|
      if @sucursal.update(sucursal_params)
        format.html { redirect_to root_path, notice: "Sucursal actualizada exitosamente" }
        format.json { render :show, status: :ok, location: @sucursal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sucursal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sucursals/1 or /sucursals/1.json
  def destroy
    @sucursal.destroy
    respond_to do |format|
      format.html { redirect_to sucursals_url, notice: "Sucursal eliminada exitosamente" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sucursal
      @sucursal = Sucursal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sucursal_params
      params.require(:sucursal).permit(:nombre, :calle, :colonia, :num_exterior, :num_interior, :codigo_postal, :ciudad, :pais, :persona_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/views/admin/index.html.erb
<%= link_to "Registrar sucursal", new_sucursal_path, class: 'btn btn-primary' %> 
<br />

app/views/empleados/_form.html.erb
<%= form_with(model: empleado, local: true, id: 'empleado_form') do |form| %>
  <% if empleado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(empleado.errors.count, "error") %> prohibited this empleado from being saved:</h2>

      <ul>
      <% empleado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sucursal_id, "Sucursal", class: 'form-label' %>
    <%= select_tag :sucursal_id, content_tag(:option, 'Seleccione una de las siguientes sucursales...',
    value: "") + options_from_collection_for_select(Sucursal.all, :id, :nombre, 
    selected: @empleado.sucursal_id), class: 'form-control', name: "empleado[sucursal_id]"%>
  </div>

  <div class="field">
    <%= form.label :nombre, "Nombre", class: 'form-label' %>
    <%= form.text_field :nombre, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :rfc, "RFC", class: 'form-label' %>
    <%= form.text_field :rfc, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :nombre_puesto, "Nombre del puesto (opcional)", class: 'form-label' %>
    <%= form.text_field :nombre_puesto, class: 'form-control' %>
  </div>

  <br />
  <%= link_to "Regresar", sucursals_path, class: 'btn btn-default float-start' %> 
  <%= form.submit button_name, class: 'btn btn-primary float-end' %>
<% end %>

<script>
$("#sucursal_id").select2({
      language: "es"
  });
  $("#empleado_form").validate({
    rules : {
      "empleado[sucursal_id]" : {
        required: true,
      },
      "empleado[nombre]" : {
        required: true,
      },
      "empleado[rfc]" : {
        required: true,
      }
    }
  });
</script>

app/views/empleados/edit.html.erb
<div class="main-card mb-3 card">
    <div class="card-header">
        <h3 class="card-title">Editar Empleado</h3>
    </div>
    <div class="card-body">
        <%= render 'form', empleado: @empleado, button_name: "Editar Empleado" %>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#empleado_rfc').prop('disabled', true);
    });
</script>

app/views/empleados/index.html.erb
<div class="main-card mb-3 card">
  <div class="card-header">
    <h3 class="card-title">Empleados</h3>
  </div>
  <div class="card-body">
    <% if @empleados.count >= 0%>
      <table id="empleados_table" class="table table-hover">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>RFC</th>
            <th>Nombre del puesto</th>
            <th>Sucursal</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @empleados.each do |empleado| %>
            <tr>
              <td><%= empleado.nombre %></td>
              <td><%= empleado.rfc %></td>
              <td><%= empleado.nombre_puesto %></td>
              <td><%= empleado.sucursal %></td>
              <td><%= link_to 'Show', empleado %></td>
              <td><%= link_to 'Edit', edit_empleado_path(empleado) %></td>
              <td><%= link_to 'Destroy', empleado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <h4>
        No existen empleados registrados
      </h4>
    <% end %>
  </div>
</div>

<br>

<%= link_to "Registrar sucursal", new_empleado_path, class: 'btn btn-primary float-end' %> 

app/views/empleados/new.html.erb
<div class="main-card mb-3 card">
    <div class="card-header">
        <h3 class="card-title">Registrar empleado</h3>
    </div>
    <div class="card-body">
        <%= render 'form', empleado: @empleado, button_name: "Registrar Empleado" %>
    </div>
</div>

app/views/empleados/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @empleado.nombre %>
</p>

<p>
  <strong>Rfc:</strong>
  <%= @empleado.rfc %>
</p>

<p>
  <strong>Nombre puesto:</strong>
  <%= @empleado.nombre_puesto %>
</p>

<% if @empleado.sucursal.present? %>
<p>
  <strong>Sucursal:</strong>
  <%= @empleado.sucursal.nombre %>
</p>
<% end %>

<%= link_to 'Edit', edit_empleado_path(@empleado) %> |
<%= link_to 'Back', empleados_path %>

app/views/layouts/_alerts.html.erb
<% if notice %>
    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                <%= simple_format(notice) %>
                <%= button_tag '', 
                    type: 'button', 
                    class: 'btn-close', 
                    aria: { label: 'Close' },
                    data: { 'bs-dismiss': 'alert'} 
                %>
            </div>
        </div>
    </div>
<% end %>

<% if alert %>
    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-danger " role="alert">
                <%= simple_format(alert) %>
                <%= button_tag '', 
                    type: 'button', 
                    class: 'btn-close', 
                    aria: { label: 'Close' },
                    data: { 'bs-dismiss': 'alert'} 
                %>
            </div>
        </div>
    </div>
<%end%>

app/views/layouts/_footer.html.erb
<hr class="featurette-divider">
<footer class="container">
    <p class="float-right">
        <a href="#">Regresar al inicio</a>
    </p>
    <p>&copy; <%=DateTime.now.strftime('%Y')%> Victor Ramos </p>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <%= link_to "Inicio", root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <%if persona_signed_in?%>
                    <li class="nav-item">
                        <%= link_to "Sucursales", sucursals_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item mt-2 mt-md-0 float-end">
                        <%= link_to "Cerrar sesión", destroy_persona_session_path, 
                        class: 'nav-link', method: 'DELETE' %>
                    </li>
                <% end %>
            </ul>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Documentos Digitales de México</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css' %>
    <%= javascript_include_tag 'https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js' %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <main role="main">
      <div class="container">
        <%= render 'layouts/alerts'%>
        <%= yield %>
      </div>
      <%= render 'layouts/footer'%>
    </main>
  </body>
</html>

app/views/sucursals/_empleados_table.html.erb
<div class="main-card mb-3 card">
  <div class="card-header">
    <h3 class="card-title">Empleados</h3>
  </div>
  <div class="card-body">
    <table id="empleados_table" class="table table-hover">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>RFC</th>
                <th>Nombre del puesto</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <% @sucursal.empleados.each do |empleado| %>
            <tr>
                <td><%= empleado.nombre %></td>
                <td><%= empleado.rfc %></td>
                <td>
                    <% if empleado.nombre_puesto.present? %>
                        <%= empleado.nombre_puesto %>
                    <% else %>
                        No asignado
                    <% end %>
                </td>
                <td>

                    <%= link_to 'Editar', edit_empleado_path(empleado), class: 'btn btn-secondary'  %>
                    <!--
                    <%= link_to 'Show', empleado %>
                    <%= link_to 'Destroy', empleado, method: :delete, data: { confirm: 'Are you sure?' } %>
                    -->
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
  </div>
</div>

<script>
$(document).ready(function() {
    $('#empleados_table').DataTable({
    "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
    },
    "columnDefs": [{
        targets: -1,
        orderable: false
    }],
    "order": [0, 'desc']
    });
});
</script>

app/views/sucursals/_form.html.erb
<%= form_with(model: sucursal, local: true, id: 'sucursal_form') do |form| %>
  <% if sucursal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sucursal.errors.count, "error") %> prohibited this sucursal from being saved:</h2>

      <ul>
      <% sucursal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :nombre, "Nombre", class: 'form-label' %>
    <%= form.text_field :nombre, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :calle, "Calle", class: 'form-label' %>
    <%= form.text_field :calle, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :colonia, "Colonia", class: 'form-label' %>
    <%= form.text_field :colonia, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :num_exterior, "Núm. exterior", class: 'form-label' %>
    <%= form.text_field :num_exterior, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :num_interior, "Núm. interior (opcional)", class: 'form-label' %>
    <%= form.text_field :num_interior, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :codigo_postal, "Código postal", class: 'form-label' %>
    <%= form.text_field :codigo_postal, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :ciudad, "Ciudad", class: 'form-label' %>
    <%= form.text_field :ciudad, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :pais, "País", class: 'form-label' %>
    <%= form.text_field :pais, class: 'form-control' %>
  </div>

  <%= form.hidden_field :persona_id, value: @persona_id %>
  <br />
  <%= link_to "Regresar", sucursals_path, class: 'btn btn-default float-start' %> 
  <%= form.submit button_name, class: 'btn btn-primary float-end' %>

<% end %>

<script defer>
  $("#sucursal_form").validate({
    rules : {
      "sucursal[nombre]" : {
        required: true,
      },
      "sucursal[calle]" : {
        required: true,
      },
      "sucursal[colonia]" : {
        required: true
      },
      "sucursal[num_exterior]" : {
        required: true,
        number: true
      },
      "sucursal[num_interior]" : {
        number: true
      },
      "sucursal[codigo_postal]" : {
        required: true,
        minlength: 5,
        maxlength: 5,
        number: true
      },
      "sucursal[ciudad]" : {
        required: true,
      },
      "sucursal[pais]" : {
        required: true,
      },
    },
    submitHandler: handleSubmit
  });
</script>

app/views/sucursals/edit.html.erb
<script>
    function handleSubmit(form){
        console.log("La verificación AJAX no se ejecutará al editar sucursal");
        form.submit();
    }
</script>

<div class="main-card mb-3 card">
    <div class="card-header">
        <h3 class="card-title">Editar sucursal</h3>
    </div>
    <div class="card-body">
        <%= render 'form', sucursal: @sucursal, button_name: "Editar Sucursal" %>
    </div>
</div>

<% if @sucursal.empleados.count > 0%>
    <%= render 'empleados_table' %>
<% end %>

app/views/sucursals/index.html.erb
<div class="main-card mb-3 card">
  <div class="card-header">
    <h3 class="card-title">Sucursales</h3>
  </div>
  <div class="card-body">
    <% if @sucursals.count > 0%>
      <table id="sucursals_table" class="table table-hover">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Número de empleados</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @sucursals.each do |sucursal| %>
            <tr>
              <td>
                <%= sucursal.nombre %>
              </td>
              <td>
                <%= sucursal.empleados.count %>
              </td>
              <td>
                <%= link_to 'Editar', edit_sucursal_path(sucursal), class: 'btn btn-secondary'  %>
                <!--
                <%= link_to 'Ver', sucursal, class: 'btn btn-default' %>
                <%= link_to 'Registrar empleado', new_empleado_path, class: 'btn btn-primary' %>
                -->
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <script>
        $(document).ready(function() {
          $('#sucursals_table').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
            },
            "columnDefs": [{
              targets: -1,
              orderable: false
            }],
            "order": [0, 'desc']
          });
        });
      </script>
    <% else %>
      <h4>
        No existen sucursales registradas
      </h4>
    <% end %>
 </div>
</div>
<br />

<div class="float-end">
  <%= link_to "Registrar Sucursal", new_sucursal_path, class: 'btn btn-primary' %> 
  <%= link_to "Registrar Empleado", new_empleado_path, class: 'btn btn-primary' %> 
</div>

app/views/sucursals/new.html.erb
<script>
    function handleSubmit(form){
        var authToken = $('meta[name=csrf-token]').attr('content');
        var nombreSucursal = $('#sucursal_nombre').val();
        $.ajax({
            type: 'POST',
            url: '<%=verificar_sucursal_path%>',
            data: {
            authenticity_token: authToken,
            nombre_sucursal: nombreSucursal
            },
            success: function(data){
            console.log(data);
            if(data != null){
                if(data){
                form.submit();
                }else{
                alert('Ya existe una sucursal registrada con el nombre proporcionado');
                }
            }else{
                alert('Por favor proporcione un nombre de sucursal válido');
            }
            },
            error: function(xhr){
            console.log(xhr.responseText);
            },
        });
        return false;
    }
</script>

<div class="main-card mb-3 card">
    <div class="card-header">
        <h3 class="card-title">Registrar sucursal</h3>
    </div>
    <div class="card-body">
        <%= render 'form', sucursal: @sucursal, button_name: "Registrar Sucursal" %>
    </div>
</div>

app/views/sucursals/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @sucursal.nombre %>
</p>

<p>
  <strong>Calle:</strong>
  <%= @sucursal.calle %>
</p>

<p>
  <strong>Colonia:</strong>
  <%= @sucursal.colonia %>
</p>

<p>
  <strong>Num exterior:</strong>
  <%= @sucursal.num_exterior %>
</p>

<p>
  <strong>Num interior:</strong>
  <%= @sucursal.num_interior %>
</p>

<p>
  <strong>Codigo postal:</strong>
  <%= @sucursal.codigo_postal %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @sucursal.ciudad %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @sucursal.pais %>
</p>

<% if @sucursal.persona.present? %>
  <p>
    <strong>Persona:</strong>
    <%= @sucursal.persona.to_text %>
  </p>
<% end %>

<%= link_to 'Edit', edit_sucursal_path(@sucursal) %> |
<%= link_to 'Back', sucursals_path %>